### ISSUE TITLE
Add AST dumps to the test suite

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/libdparse#143]
- [ ] add a simple XML output (like Dscanner, or maybe even use dscanner)
- [ ] add AST dumps to fix results and improve code coverage

Related to #129

**Comment by Hackerpilot** [comment]
To check that AST nodes are being generated correctly we will need to make a test system that can be given a bunch of source code, and then corresponding ASTs, or queries against the generated AST, that should match.

One way to do this is to create some sort of AST query testing tool and then make a set of unit tests in the code.

Another way, which I like because it's lazier, is to move the `dscanner.astprinter` module from the D-Scanner project into libdparse, and then create a small testing program that will read in code and the output the AST in XML format. We can then re-use the tree querying functionality of the xmllint program by writing a script that takes test files and a set of XPath expressions to run on it. We'd have to make sure that the CI systems are configured to install the xmllint tool, but I don't think that should be too difficult.

**Comment by wilzbach** [comment]
> Another way, which I like because it's lazier, is to move the dscanner.astprinter module from the D-Scanner project into libdparse,

I would go/vote for this one :+1:
