### ISSUE TITLE
An EponymousTemplateDeclaration is never parsed

### ISSUE THREAD

**Issue by pirocks** [dlang-community/libdparse#165]
There seems to be a method/rule called `EponymousTemplateDeclaration`. The documentation provides a grammar specification, however it seems to be different from the official D definition of an Eponymous Template. It also appears that declarations like `enum foo(T) = bar!T;`, are not parsed as an `EponymousTemplateDeclaration`, but instead parsed as  `AutoDeclarationPart`. Is this a bug or/and when should I expect a EponymousTemplateDeclaration to be parsed?

**Comment by BBasile** [comment]
Everything that has template parameters can be rewritten as a template. If we rewrite your example we have

```d
template foo(T)
{
    enum foo = bar!T
}
```

which is an eponymous template. The rule in D does not exist but it makes sense. But it seems that there's a bug in the parser because as you noted your example is not parsed as an EponymousTemplateDeclaration.
