### ISSUE TITLE
Function literal parsed as struct initialization

### ISSUE THREAD

**Issue by pirocks** [dlang-community/libdparse#170]
The following:
```d
int function() func = {
    return 6;
};
```

parses as;

```xml
<module>
    <declaration>
        <variableDeclaration>
            <type pretty="int function()">
                <type2>int</type2>
                <function/>
                <parameters>
                </parameters>
            </type>
            <declarator line="1">
                <name>func</name><initializer>
                <nonVoidInitializer>
                    <structInitializer>
                        <structMemberInitializers>
                        </structMemberInitializers>
                    </structInitializer>
                </nonVoidInitializer>
            </initializer>
            </declarator>
        </variableDeclaration>
    </declaration>
</module>
```

Which does not seem to be correct.

**Comment by BBasile** [comment]
It's related to https://github.com/dlang-community/libdparse/issues/49. I think that dparse should indicates another limitation, that is that  the empty parens pair is required in function literals (and maybe this should be proposed as D enhancement too)

That being said, this doesn't mean that it's not fixable. The problem is just that it's yet another case where many lookups are needed.

**Comment by BBasile** [comment]
In `parseNonVoidInitializer` previous tokens must be checked to see if we have `function() =`. Fortunately there's only this case that causes the bug. Once there are parameters it disappears.

**Comment by pirocks** [comment]
I take it this is now solved.
