### ISSUE TITLE
Add optional offset to peekIs or add overload that takes an offset.

### ISSUE THREAD

**Issue by Hackerpilot** [dlang-community/libdparse#246]
Should clean up code like `tokens[index + 2].type == tok!","`. Once the new version of `peekIs` is added, audit the parser code to figure out where it should be used. We've been getting a decent number of range error bug reports lately and this should help prevent some in the future.

**Comment by BBasile** [comment]
Ranges errors were there since forever but it's only since very recently that people have started using indirectly dparse on invalid code, thanks to the support for dynamic linting in several editors.

But yeah this refactoring has to done. Still better to have a call rather than a complex expression copied and paste N times.
