### ISSUE TITLE
Incomplete UnaryExpression for AutoDeclaration

### ISSUE THREAD

**Issue by ryuukk** [dlang-community/libdparse#482]
UnaryExpression from AutoDeclaration seems incomplete, it's all empty:

![devenv_BsJaGyfbs0](https://user-images.githubusercontent.com/44361234/217651103-61e05005-76cc-422c-b9dd-85e691dc0775.png)

There is a //TODO note in the code that indicates that it's WIP

This is blocking me for https://github.com/dlang-community/DCD/pull/709

https://github.com/dlang-community/libdparse/blob/88f247e0a18ec0a757989c4be6fd22c81314f152/src/dparse/ast.d#L3427-L3454

**Comment by WebFreak001** [comment]
what code are you trying to parse? In your debugger screenshot it seems like functionCallExpression is set, so it doesn't seem invalid to me at first glance at least.

**Comment by WebFreak001** [comment]
closing due to missing information / screenshot not showing what the error is - this is likely just that the information is elsewhere than in the UnaryExpression, but I don't know what it should be.

If you don't find the information, please reopen and post what code you are trying to parse that doesn't work.
